[package]
name = "ruoscript"
version = "0.1.0"
authors = ["Ilya Bogdanov <ilya.bogdanov@xdev.re>"]

[dependencies]
log = "0.4.5"
env_logger = "0.5.13"
failure = "0.1.2"
failure_derive = "0.1.2"
llvm-sys = "70.0.0"
libc = "0.2"

[dev-dependencies]
env_logger = "0.5.13"

